name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy # Change to 'main' if your default branch is main

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run build    # produce ./build (or change path below)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build    # point to your build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1